### ISSUE TITLE
multiple time slots are not filtered

### ISSUE THREAD

**Issue by gludington** [MykeMyke/webCalendar#155]
At least as I think it is intended. If I check for "Midnight-4AM" I get games starting between - you got it - Midnight and 4 AM. The others also work fine. Separately. As soon as I click more than one box for the times, it seems to mess up and get it wrong. If I check "noon - 4 PM" and "4PM - 8PM" I get games starting 1 and 4 AM, as well as withing the checked box span. It is not a very big deal, but it would be nice to be able to check more than one timespan at once.

**Comment by gludington** [comment]
https://github.com/MykeMyke/TridenGamesWebsite/pull/156

**Comment by MykeMyke** [comment]
Closed by #156
